### ISSUE TITLE
repo beschrijving

### ISSUE THREAD

**Issue by moorlag** [Cookien00b/Hexapawn#4]
Beschrijf in de repo beschrijving de essentie van het project. Dat zorgt ervoor dat bezoekers direct weten wat Hexapawn doen/zou moeten doen/misschien gaat doen/hopelijk ooit gaat doen*. 

*doorhalen wat niet van toepassing is.

**Comment by MBrinks2239** [comment]
Ik heb het aangepast zodat het duidelijk is wat Hexapawn_AI zou moeten doen.
